### PR TITLE
Fetch Classifications by user_id

### PR DESCRIPTION
**Pull request by amyrebecca**

### CODE REVIEW

**Comment by zwolf** [comment]
Can you add a spec for this method?

also you should add us both as authors to the gemspec :P 🥇

**Comment by amyrebecca** [comment]
both good ideas, will do :) might as well spec the other method in this class as well

**Comment by zwolf** [comment]
It's already specced, though not in great detail. just confirming it's sending the request and getting the response that you expect.

https://github.com/zooniverse/panoptes-client.rb/blob/375d5dab04bd4083252bdce48095d58f776e90c2/spec/panoptes/client/classifications_spec.rb#L4

**Comment by amyrebecca** [comment]
okay should be good to go now

**Comment by zwolf** [comment]
lgtm :shipit:

**Pull request merged**
