### PR TITLE
Add Cellect endpoints

### PR DESCRIPTION
**Pull request by parrish**
With the current implementation, it's not very possible to make non-`/api` and non json-api calls.

Happy to move those `json_` methods somewhere else if you like.

### CODE REVIEW

**Comment by parrish** [comment]
Oh, god, @houndci-bot, shut up.

**Comment by marten** [comment]
I think if you have a look at https://github.com/zooniverse/panoptes-client.rb/pull/5/files it should fix both Hound and your issue with `/api` since I moved the prefixing to the individual clients.

**Comment by parrish** [comment]
Yeah, #5 should probably go before this then.  I'll still have to workaround the path / mime type issues though.

**Comment by marten** [comment]
I've merged #5 so have a go at refactoring to make the path/mime issues go into the individual application faradays. That's probably the best way forward.

**Comment by camallen** [comment]
@parrish you got any time to work on this? If not i can try and get to this on thurs.

**Comment by parrish** [comment]
Yep.  Working through the new changes from #5.  I've got some refactoring coming too.

**Comment by camallen** [comment]
excellent

**Comment by parrish** [comment]
Hmm... looks like Hound didn't pickup the new settings

**Comment by parrish** [comment]
Other than hound barfing all over this (`rubocop` is pretty clean), this is basically just drying things up and keeping the abstractions flexible.

**Comment by camallen** [comment]
LGTM

**Comment by parrish** [comment]
@camallen: Documentation is updated now.

**Comment by camallen** [comment]
LGTM

**Pull request merged**
