### PR TITLE
Workflows and subject sets management

### PR DESCRIPTION
**Pull request by marten**
The EduAPI will use these to clone the main workflow, create a subject set for it, and assign subjects to it (subject ids for that will come from CartoDB queries)

### CODE REVIEW

**Comment by camallen** [comment]
LGTM - cloning workflows across projects already is supported in the API, http://docs.panoptes.apiary.io/#reference/projects/project-create-links/add-a-link in project cloning has a bug where it overwrites any existing workflows instead of appending.

**Comment by marten** [comment]
Interesting, I knew I'd seen cloning somewhere but couldn't find it because I was looking at the workflows controller/docs.

**Comment by marten** [comment]
Not that it helps, we need to do it for the same project.

**Comment by camallen** [comment]
Right - well this works fine and it's what PFE does too.

**Pull request merged**
